# Generated by Django 4.2.1 on 2023-05-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.IntegerField(verbose_name='버스번호')),
                ('bus_time', models.TimeField(verbose_name='출발시간')),
            ],
        ),
    ]
