# Generated by Django 4.2.1 on 2023-05-16 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DownBus', '0002_nowday_buslist_day_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buslist',
            name='day_type',
            field=models.ForeignKey(default='WEEK', on_delete=django.db.models.deletion.CASCADE, to='DownBus.nowday', verbose_name='요일'),
        ),
        migrations.AlterField(
            model_name='nowday',
            name='day_type',
            field=models.CharField(choices=[('WEEK', '주중'), ('SAT', '토요일'), ('SUN', '일요일/공휴일')], max_length=4, verbose_name='요일'),
        ),
    ]
