# Generated by Django 4.2.1 on 2023-05-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('routeId', models.CharField(max_length=50)),
                ('staOrder', models.CharField(max_length=50)),
            ],
        ),
    ]
